#!/bin/bash
# xhorakt00 Tadeas Horak
# 7. 3. 2024

export POSIXLY_CORRECT=yes
export LC_ALL=C

DATE_TIME_REGEX="^([0-9]{4})-([0-9]{1,2})-([0-9]{1,2}) ([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2})$"

HELP="0" #dont like this :( but it doesn't work without it :((

AFTER=""
BEFORE=""
CURRENCY=""
USER=""
FILE=""

help(){
    echo "xtf [-h|--help] [FILTR] [PŘÍKAZ] UŽIVATEL LOG [LOG2 [...]"
    echo "PŘÍKAZ může být jeden z:
list – výpis záznamů pro daného uživatele.
list-currency – výpis seřazeného seznamu vyskytujících se měn.
status – výpis skutečného stavu účtu seskupeného a seřazeného dle jednotlivých měn.
profit – výpis stavu účtu zákazníka se započítaným fiktivním výnosem.
FILTR může být kombinace následujících:
-a DATETIME – after: jsou uvažovány pouze záznamy PO tomto datu a čase (bez něj). DATETIME je formátu YYYY-MM-DD HH:MM:SS.
-b DATETIME – before: jsou uvažovány pouze záznamy PŘED tímto datem a časem (bez něj).
-c CURRENCY – jsou uvažovány pouze záznamy odpovídající dané měně.
-h a --help vypíšou nápovědu s krátkým popisem každého příkazu a přepínače."
}

list(){
    AWKARG=""
    if [[ ! -z $AFTER ]] ; then
        AWKARG="\$2 > after"
    fi
    if [[ ! -z $BEFORE ]] ; then
        if [[ ! -z $AWKARG ]] ; then
            AWKARG+=" && \$2 < before"
        else
            AWKARG="\$2 < before"
        fi
    fi
    if [[ ! -z $CURRENCY ]] ; then
        if [[ ! -z $AWKARG ]] ; then
            AWKARG+=" && \$3 == currency"
        else
            AWKARG="\$3 == currency"
        fi
    fi
    echo "$(awk -v after="$AFTER" -v before="$BEFORE" -v currency="$CURRENCY" -F ';' "$AWKARG" $FILE)"
}


while getopts ":-:a:b:c:h" opt #a+arg, b+arg, c+arg, h (no arg), -+arg (used for --help)
do 
    case "$opt" in 
        h)
            HELP="1"    #tried to do this with OPTIND != 2, but it just refuses to work, idk just kill me
            ;;
        -)  
            case $OPTARG in 
                help)       #only accepting --help
                    help
                    exit 0
                    ;;
                *)
                    echo "Invalid syntax" >&2
                    exit 1
            esac
            ;;
        a)
            if [[ ! "$OPTARG" =~ $DATE_TIME_REGEX ]] ; then
                echo "Incorrect date or time format!" >&2
                exit 1
            fi
            AFTER=$OPTARG
            ;;

        b)
            if [[ ! "$OPTARG" =~ $DATE_TIME_REGEX ]] ; then
                echo "Incorrect date or time format!" >&2
                exit 1
            fi
            BEFORE=$OPTARG
            ;;

        c) CURRENCY=$OPTARG
           ;;

        *)
            echo "Invalid* syntax" >&2
            exit 1
            ;;
    esac
done
if [ "$HELP" -eq "1" ] ; then
    help
    exit 0
fi
if [ ! -z "$AFTER" ] ; then
    echo "after: $AFTER"
    shift 2
fi
if [ ! -z "$BEFORE" ] ; then
    echo "before: $BEFORE"
    shift 2
fi
if [ ! -z "$CURRENCY" ] ;  then
    echo "currency: $CURRENCY"
    shift 2
fi
USER=$2
FILE=$3
case "$1" in 
    list)   
        list
        ;;
    list-currency)
        list-currency
        ;;
    status)
        status
        ;;
    profit)
        profit
        ;;
    *)  
        echo "NO command, use list, dont shift"
        USER=$1
        FILE=$2
        list
        ;;
esac
#user = $1
#file = $2
